version: '3.8'
services:
    ratings:
        container_name: ratings
        restart: always
        image: rayos006/ratings:latest
        environment:
            - PLEX_ADDRESS=http://PLEX_IP:32400
            - PLEX_TOKEN=SomeSecret
            - PLEX_TV_LIBRARY=TV Shows
            - PLEX_MOVIE_LIBRARY=Movies
            - PLEX_DB_LOCATION=/path/to/plex/library
            - PLEX_DB_NAME=plex_db_name
            - DRY_RUN=False
            - MOVIES=True
            - TV=True